name: Build
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/README.md'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Simple poetry build no package
      run: poetry build

